### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by s-cai** [s-cai/pikachu#1]
- [ ] level 2 market data
  - [ ] dump
  - [ ] maybe process in pickle
- [ ] A properly written naive bot
